Algoritmo "semnome"

Var
  sigla : caractere


Inicio
     escreval("digite a sigla: ")
     leia(sigla)
     se ( sigla = "rj") entao
     escreval("carioca: ")
     senao
     se (sigla = "sp") entao
     escreval("paulista: ")
     senao
     se ( sigla = "mg")entao
     escreval("mineiro: ")
     senao
     escreval("outros estados: ")
     fimse
     fimse
     fimse


Fimalgoritmo